### ISSUE TITLE
/usr/bin/install_name_tool: more than one input file specified (@loader_path/../lib and -add_rpath)

### ISSUE THREAD

**Issue by barracuda156** [eddelbuettel/rcppclassic#12]
```
/opt/local/bin/gcc-mp-12 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -fPIC  -pipe -Os -arch ppc  -c init.c -o init.o
/opt/local/bin/g++-mp-12 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -L/opt/local/lib -lMacportsLegacySupport -arch ppc -o RcppClassic.so RcppDate.o RcppDateVector.o RcppDatetime.o RcppDatetimeVector.o RcppFrame.o RcppFunction.o RcppList.o RcppNumList.o RcppParams.o RcppResultSet.o RcppStringVector.o RcppStringVectorView.o copyMessageToR.o init.o -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
/opt/local/bin/g++-mp-12 -std=gnu++14 -o libRcppClassic.dylib RcppDate.o RcppDateVector.o RcppDatetime.o RcppDatetimeVector.o RcppFrame.o RcppFunction.o RcppList.o RcppNumList.o RcppParams.o RcppResultSet.o RcppStringVector.o RcppStringVectorView.o copyMessageToR.o init.o -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress   -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
/usr/bin/install_name_tool: more than one input file specified (@loader_path/../lib and -add_rpath)
Usage: /usr/bin/install_name_tool [-change old new] ... [-id name] input
make: *** [libRcppClassic] Error 1
ERROR: compilation failed for package ‘RcppClassic’
```

**Comment by eddelbuettel** [comment]
Hm.  Can you try to add debug messages there and create standard output?  These are code lines that have worked unchanged for a decade+.

**Comment by eddelbuettel** [comment]
Here under Ubuntu 22.04 straight from the repo:

```sh
edd@rob:~/git/rcppclassic(master)$ install.r  # simple wrapper from littler
* installing *source* package found in current working directory ...
* installing *source* package ‘RcppClassic’ ...
** using staged installation
** libs
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppDate.cpp -o RcppDate.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppDateVector.cpp -o RcppDateVector.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppDatetime.cpp -o RcppDatetime.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppDatetimeVector.cpp -o RcppDatetimeVector.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppFrame.cpp -o RcppFrame.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppFunction.cpp -o RcppFunction.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppList.cpp -o RcppList.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppNumList.cpp -o RcppNumList.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppParams.cpp -o RcppParams.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppResultSet.cpp -o RcppResultSet.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppStringVector.cpp -o RcppStringVector.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppStringVectorView.cpp -o RcppStringVectorView.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c copyMessageToR.cpp -o copyMessageToR.o
ccache gcc -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes -std=gnu99 -c init.c -o init.o
ccache g++ -Wl,-S -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o RcppClassic.so RcppDate.o RcppDateVector.o RcppDatetime.o RcppDatetimeVector.o RcppFrame.o RcppFunction.o RcppList.o RcppNumList.o RcppParams.o RcppResultSet.o RcppStringVector.o RcppStringVectorView.o copyMessageToR.o init.o -L/usr/lib/R/lib -lR
ccache g++ -o libRcppClassic.so RcppDate.o RcppDateVector.o RcppDatetime.o RcppDatetimeVector.o RcppFrame.o RcppFunction.o RcppList.o RcppNumList.o RcppParams.o RcppResultSet.o RcppStringVector.o RcppStringVectorView.o copyMessageToR.o init.o -Wl,-S -shared    -L"/usr/lib/R/lib" -lR
ar qc libRcppClassic.a RcppDate.o RcppDateVector.o RcppDatetime.o RcppDatetimeVector.o RcppFrame.o RcppFunction.o RcppList.o RcppNumList.o RcppParams.o RcppResultSet.o RcppStringVector.o RcppStringVectorView.o copyMessageToR.o init.o
cp libRcppClassic.so ../inst/lib
cp libRcppClassic.a ../inst/lib
rm libRcppClassic.so libRcppClassic.a
installing to /usr/local/lib/R/site-library/00LOCK-rcppclassic/00new/RcppClassic/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RcppClassic)
edd@rob:~/git/rcppclassic(master)$ 
```

**Comment by barracuda156** [comment]
I have no idea if Linux even supports rpaths. I will try getting debug output tomorrow.

This may be due to some interaction of Macports with the package, but at the same time I have built about 300 R packages in identical environment, and this is the only case of getting such an error.

**Comment by eddelbuettel** [comment]
It's not one that matters, but we should still look into it. I injected a line just doing 'echo ...' before the `install_name_tool` line and it works fine here.  I am sure we'll get to it but I will need your hand for some local probing.  Also, as always, good to check CRAN status at https://cloud.r-project.org/web/checks/check_results_RcppClassic.html which is fine:

![image](https://user-images.githubusercontent.com/673121/214956723-cf573921-cf27-4676-b16d-183e5014ee49.png)

**Comment by barracuda156** [comment]
@eddelbuettel Here is the build log.
[RcppClassic_build.log](https://github.com/eddelbuettel/rcppclassic/files/10513970/RcppClassic_build.log)

Build settings are picked from here: https://github.com/macports/macports-ports/commit/11ef9629518c3d47d445094be20443d2a3542cda
There is no additional customization set in the portfile and no patches applied.

**Comment by eddelbuettel** [comment]
But that's not reproducible beyond your setup, does not affect CRAN, and does not put me in a position to be able to debug.   What do you expect me to do here?   :man_shrugging:

**Comment by barracuda156** [comment]
For the context, I am bringing R packages into Macports. So it is relevant beyond my personal setup.

I need to find some info on how to get debugging info with R. I will deal with that after I have some sleep :)

**Comment by eddelbuettel** [comment]
Could the r-sig-mac list be of help?  I am not a mac user by any stretch...

**Comment by barracuda156** [comment]
@eddelbuettel Got it. I appreciate that you are responding.

Let me see first on my end if I can find a solution. These rpaths are a mac thing.

**Comment by eddelbuettel** [comment]
Yes they are and it all goes back to help I once got from Simon to make things work there.  But he too is opinionated and insists on his toolchain for macOS os your macports may be considered a "port" we have to work out.

**Comment by barracuda156** [comment]
@eddelbuettel Could you say what was the reason for this commit? https://github.com/eddelbuettel/rcppclassic/commit/c8ca1e64c5b1ca540cdf00968b1050c723263dfc
Reverting it fixes the build.

P. S. I probably miss something, but two things look strange to me:
1. Makevars sets `all: $(SHLIB) userLibrary`, but target SHLIB is not defined, while userLibrary target includes both static and dynamic libs already.
2. `inline.R` states that static is default on macOS, which appears to not be the case, and uses rpath for Linux only (why?).

**Comment by eddelbuettel** [comment]
> Could you say what was the reason for this commit?

That I was being yelled at by CRAN for using an absolute URL (and I then checked and noticed that my other uses were in fact relative.

Re 1:  Target $(SHLIB) is inherited. Many/most snipped `src/Makevars` (note the name !!) work that way as they "behind the scenes accumulated into an actual `src/Makefile` around the fragment supplied by R.  Very common -- so this is not an issue at all.

Re 2:  I am not sure what you are saying. `install_name_tool` appears to present only on macOS (aka "darwin"), we condition its use on being present ... which as best as I can tell is false on all Linux system I have seen in 25+ years.

We use the test for "is `install_name_tool` present in a few other packages.  That said we also use a variant that starts with

     if [ "$(OS)" != "Windows_NT" ] && [ `uname -s` = 'Darwin' ] && ...

and then tests for the file it modifies.

Your initial error report sounded like the call went wrong ("two arguments when one expected") and I suggested you echo it to see what runs.  Did you get a chance to do that?

**Comment by barracuda156** [comment]
Thank you for responding. I tried to find info on verbose output in R, but it does not seem to be easily available. There is apparently `--no-echo` option, but reverse does not work: I added `--echo`, and it is not recognized. Could you advise me how to pass a needed argument?

**Comment by eddelbuettel** [comment]
Sorry.  What I suggested (and did myself) was essentially a simple 

```diff
modified   src/Makevars
@@ -30,6 +30,7 @@ userLibrary: 	$(USERLIB) $(USERLIBST)
 $(USERLIB): 	$(OBJECTS)
 		$(SHLIB_CXXLD) -o $(USERLIB) $^ $(SHLIB_CXXLDFLAGS) $(ALL_LIBS)
 		@if test -e "/usr/bin/install_name_tool"; then /usr/bin/install_name_tool -add_rpath @loader_path/../lib$(R_ARCH) $(USERLIB); fi
+		echo "Running /usr/bin/install_name_tool -add_rpath @loader_path/../lib$(R_ARCH) $(USERLIB)"
 #		@if test -e "/usr/bin/strip" & test -e "/bin/uname" & [[ `uname` == "Linux" ]]; then /usr/bin/strip --strip-unneeded $(USERLIB); fi
 
```

and then doing `R CMD INSTALL .` to see what gets echoed.  For you, the line errors.  For every CRAN system (and other systems) it works.  Maybe we can find the cause at your end?

**Comment by barracuda156** [comment]
Here is what I get:
```
/opt/local/bin/gcc-mp-12 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include   -fPIC  -pipe -Os -arch ppc  -c init.c -o init.o
/opt/local/bin/g++-mp-12 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -L/opt/local/lib -lMacportsLegacySupport -arch ppc -o RcppClassic.so RcppDate.o RcppDateVector.o RcppDatetime.o RcppDatetimeVector.o RcppFrame.o RcppFunction.o RcppList.o RcppNumList.o RcppParams.o RcppResultSet.o RcppStringVector.o RcppStringVectorView.o copyMessageToR.o init.o -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
/opt/local/bin/g++-mp-12 -std=gnu++14 -o libRcppClassic.dylib RcppDate.o RcppDateVector.o RcppDatetime.o RcppDatetimeVector.o RcppFrame.o RcppFunction.o RcppList.o RcppNumList.o RcppParams.o RcppResultSet.o RcppStringVector.o RcppStringVectorView.o copyMessageToR.o init.o -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress   -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
/usr/bin/install_name_tool: more than one input file specified (@loader_path/../lib and -add_rpath)
Usage: /usr/bin/install_name_tool [-change old new] ... [-id name] input
make: *** [libRcppClassic] Error 1
ERROR: compilation failed for package ‘RcppClassic’
* removing ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RcppClassic/R-RcppClassic/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppClassic’
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RcppClassic/R-RcppClassic/work/RcppClassic_0.9.13" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RcppClassic/R-RcppClassic/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library 
Exit code: 1
```

**Comment by eddelbuettel** [comment]
Reorder: I added the line _after the one that fails_ which is a bad idea because we do not get to it.  Try it the other way around i.e. move it above.

**Comment by barracuda156** [comment]
```
/opt/local/bin/g++-mp-12 -std=gnu++14 -o libRcppClassic.dylib RcppDate.o RcppDateVector.o RcppDatetime.o RcppDatetimeVector.o RcppFrame.o RcppFunction.o RcppList.o RcppNumList.o RcppParams.o RcppResultSet.o RcppStringVector.o RcppStringVectorView.o copyMessageToR.o init.o -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress   -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
echo "Running /usr/bin/install_name_tool -add_rpath @loader_path/../lib libRcppClassic.dylib"
Running /usr/bin/install_name_tool -add_rpath @loader_path/../lib libRcppClassic.dylib
/usr/bin/install_name_tool: more than one input file specified (@loader_path/../lib and -add_rpath)
Usage: /usr/bin/install_name_tool [-change old new] ... [-id name] input
make: *** [libRcppClassic] Error 1
ERROR: compilation failed for package ‘RcppClassic’
```

**Comment by eddelbuettel** [comment]
That seems to be the correct invocation for other OSs.  Next test:  Comment it out (and remove the echo line).

If that works then we need another condition as in 

     if [ "$(OS)" != "Windows_NT" ] && [ `uname -s` = 'Darwin' ] && ...

**Comment by barracuda156** [comment]
> That seems to be the correct invocation for other OSs.
> 
> Next test: Comment it out (and remove the echo line).

Your earlier version with `-id $(R_PACKAGE_DIR)/lib$(R_ARCH)/$(USERLIB)` works perfectly fine (in a sense the build completes).
I can try removing the line altogether and let you know how that works.

Let me also check if it loads correctly.

> If that works then we need another condition as in
> 
> ```
>  if [ "$(OS)" != "Windows_NT" ] && [ `uname -s` = 'Darwin' ] && ...
> ```

Maybe rpath can be used instead? It allows to accomplish everything needed and more: http://clarkkromenaker.com/post/library-dynamic-loading-mac/
CMake switched to rpaths by default long back: https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_RPATH.html#prop_tgt:MACOSX_RPATH

Downside: rpaths do not work on Tiger (not a big concern, IMO, but I have to mention).

> Also: do you have a file `libRcppClassic.dylib` or is `libRcppClassic.so` for you?

`libRcppClassic.dylib`

**Comment by eddelbuettel** [comment]
As mentioned, I was asked to make the change, and I cannot revert this as CRAN is (way) more import for (essentially all) R users than your macports initiative.  

I will try my best to accomodate you, but this is your deployment bug so I will have to rely on _you_ to find a patch and setting that works for you.  It maybe as simple as an OS or compiler check _if_ there is something distinctive.  If not, maybe you need to think about a layer of patches you allow yourself to apply to source packages and that with this one.  Just a thought -- other bulk build systems do it too.

**Comment by eddelbuettel** [comment]
I am not sure why this only returns four matches (and _e.g._ ignores `data.table`) but there are a few more variants.

https://github.com/search?q=org%3Acran+install_name_tool&type=code&l=Makefile

You could check what works on your end, or maybe find a condition under which we would skip the failing step.

**Comment by eddelbuettel** [comment]
Closing this as stale.

**Comment by barracuda156** [comment]
@eddelbuettel Sorry, this was eventually forgotten. No need to re-open the issue, I will update on it if I find a suitable solution.
Thank you!
