### ISSUE TITLE
Incomplete installation with --merge-multiarch (regression)

### ISSUE THREAD

**Issue by sneumann** [eddelbuettel/rcppclassic#3]
Hi,

On an up-to-date R, packages can't link to RcppClassic if RcppClassic is installed 
with `--merge-multiarch` as is the case on the BioC build machines. The first part 
of the installation for i386 succeeds:

http://bioconductor.org/checkResults/devel/bioc-LATEST/Rdisop/moscato2-install.html

```
C:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o Rdisop.dll tmp.def disop.o imslib/src/ims/element.o [...] imslib/src/ims/nitrogenrulefilter.o E:/biocbld/bbs-3.3-bioc/R/library/RcppClassic/lib/i386/libRcppClassic.a -Lc:/local323/lib/i386 -Lc:/local323/lib -LE:/biocbld/BBS-3˜1.3-B/R/bin/i386 -lR
```

but the second part for x64 fails:

```
C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o Rdisop.dll tmp.def disop.o imslib/src/ims/element.o [...]imslib/src/ims/nitrogenrulefilter.o -Lc:/local323/lib/x64 -Lc:/local323/lib -LE:/biocbld/BBS-3˜1.3-B/R/bin/x64 -lR
Error in tools::file_path_as_absolute(base::system.file(..., package = "RcppClassic")) : 
  file '' does not exist
```

Dan Tenenbaum reported that:

> > > OK, I think I've sorted this out. On our build system dependencies
> > > are usually installed with the --merge-multiarch flag but that
> > > doesn't work with RcppClassic, results in the .a file being missing for x64. 
> > > I installed it without that flag and Rdisop installs and builds.

The `Makevars.win` line is 

```
PKG_LIBS=`${R_HOME}/bin/Rscript -e "RcppClassic:::LdFlags()" ` `${R_HOME}/bin/Rscript -e "Rcpp:::LdFlags()"` 
```

This setup still works on http://bioconductor.org/checkResults/release/bioc-LATEST/Rdisop/
Can i work around this with an update to my Makevars.win ?

Yours,
Steffen

**Comment by dtenenba** [comment]
So now that CRAN's contributed packages are available as binaries built under the new toolchain, we can just install the binary of RcppClassic and Rdisop installs just fine. I think this is what the build system will do by default (as long as the source version of RcppClassic is not newer than the windows binary) so maybe we are ok....

**Comment by eddelbuettel** [comment]
You may be on your own here.  None of the R infrastructure I stand behind (for Debian) is (explicitly) supporting multiarch.  For Windows we just follow CRAN.  And have been since the mid-2000s.
If it turns out that this may be fixable with small steps in local package, pull requests may be welcome.

But if this is systematic ... you may be on your own.   I don;t work on Windows so very little input I can provide here.

**Comment by eddelbuettel** [comment]
Closing what seems to be a very dormant issue.
